export const CREATE_TEAM = 'CREATE_TEAM';
export const CREATE_TEAM_USER = 'CREATE_TEAM_USER';
export const DELETE_TEAM_USER = 'DELETE_TEAM_USER';
export const FETCH_TEAM = 'FETCH_TEAM';
export const FETCH_TEAM_USER = 'FETCH_TEAM_USER';